Update README.md
tmysmmr/chat-space pull request #1
Opened 2019-08-11 09:53 UTC by tmysmmr

2019-08-11 09:56 UTC, hirokichi123 commented
WHATとWHYを書きましょう

2019-08-11 09:57 UTC, hirokichi123 requested changes

2019-08-11 09:57 UTC, hirokichi123 commented on README.md
> +|group_name|string|null: false|
nameでいいかと思います

2019-08-11 09:57 UTC, hirokichi123 commented on README.md
> +## group table
不要なカラムがあるので、見直してみましょう

2019-08-11 09:57 UTC, hirokichi123 commented on README.md
> +## member table
これは何のためのテーブルですか？

2019-08-11 10:07 UTC, hirokichi123 requested changes
コメントには返信かリアクションをしましょう。
また、コメントした部分に対しての修正ができていない部分があるので、
そこを修正しましょう

2019-08-11 22:48 UTC, TOMARUMARU commented on README.md
> +## user table
usersですね

2019-08-11 22:48 UTC, TOMARUMARU commented on README.md
> +## group table
groupsですね

2019-08-11 22:48 UTC, TOMARUMARU commented on README.md
> +|user_id|integer|null: fasle, foreign_key: true|
user_idは不要です

2019-08-11 22:48 UTC, TOMARUMARU commented on README.md
> +- has_many :users
多対多のアソシエーションを組んでください

2019-08-11 22:48 UTC, TOMARUMARU commented on README.md
> +|group_id|integer|null: fasle, foreign_key: true|
型はreferencesにしましょう

2019-08-11 22:48 UTC, TOMARUMARU commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
こちらも

2019-08-11 22:48 UTC, TOMARUMARU commented on README.md
> +|user_id|integer|null: fasle, foreign_key: true|
こちらも

2019-08-11 22:48 UTC, TOMARUMARU commented on README.md
> +|group_id|integer|null: false, foreign_key: true|
こちらも

2019-08-12 05:25 UTC, tmysmmr commented on README.md
> +## user table
ありがとうございます。users tableに訂正しました。

2019-08-12 05:25 UTC, tmysmmr commented on README.md
> +|user_id|integer|null: fasle, foreign_key: true|
user_id削除しました。

2019-08-12 05:25 UTC, tmysmmr commented on README.md
> +- has_many :users
has_many :usersにアソシエーションを組みました。

2019-08-12 05:25 UTC, tmysmmr commented on README.md
> +|group_id|integer|null: fasle, foreign_key: true|
message tableの外部キーgroup_idとuser_idの型をreferencesに変更しました。

2019-08-12 05:26 UTC, tmysmmr commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
変更しました。

2019-08-12 05:26 UTC, tmysmmr commented on README.md
> +|user_id|integer|null: fasle, foreign_key: true|
変更しました。

2019-08-12 05:26 UTC, tmysmmr commented on README.md
> +|group_id|integer|null: false, foreign_key: true|
変更しました。外部キーの型はreferences！勉強になりました。
添削宜しくお願いいたします。

2019-08-12 05:29 UTC, miyagit commented on README.md
> +
アソシエーションを追加しましょう。

2019-08-12 05:38 UTC, tmysmmr commented on README.md
> +
has_many :membersをアソシエーション追加しました。
添削お願いいたします。

2019-08-12 05:46 UTC, shingoteshima commented
lgtm

2019-08-12 05:56 UTC, merged