メッセージ送信機能を非同期通信をしよう！
tmysmmr/chat-space pull request #4
Opened 2019-09-08 10:29 UTC by tmysmmr

https://gyazo.com/61b7ab7c61a542c85894498babbd8c80

お疲れ様です。動画キャプチャ初めてやりますが確認できますでしょうか？
宜しくお願いいたします。

2019-09-08 10:31 UTC, yuki-uchida requested changes
public以下は上げないようにしましょう

2019-09-08 10:31 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +    .done(function(data){
dataではなくより具体的な名前にしましょう

2019-09-08 10:32 UTC, yuki-uchida commented
動画キャプチャは問題なく見れます！

2019-09-08 14:49 UTC, tmysmmr commented on app/assets/javascripts/message.js
> +    .done(function(data){
messageに変更しました。

2019-09-09 02:04 UTC, TOMARUMARU reviewed
public/uploads以下のファイルをこちらのPRから除きましょう

2019-09-09 02:04 UTC, TOMARUMARU commented on app/assets/javascripts/message.js
> +      $('.input-box__image__file').val('')
resetメソッドを使いましょう

2019-09-11 11:31 UTC, tmysmmr commented on app/assets/javascripts/message.js
> +      $('.input-box__image__file').val('')
resetメソッドに変更しました。
変更しているのですが、もしかしてプルリク上手くいっていませんでしょうか？

2019-09-11 11:33 UTC, i-date approved these changes
LGTMとさせていただきます^^

2019-09-11 11:39 UTC, merged